apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: Opaque
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBUzVLV0M1UFFSQ1BaQktFWQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSAyeXdqYVJvTng3aFpDZ3pZMzBLU2prclluOWwxUGE0NTNIMkY5ZTdl
