apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: udagram-backend-user
 name: udagram-backend-user
 namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-backend-user
  template:
    metadata:
      labels:
        app: udagram-backend-user
    spec:
      containers:
      - image: thecoderocket/udagram-api-user:v1
        name: udagram-backend-user
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret 