apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: udagram-backend-feed
 name: udagram-backend-feed
 namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-backend-feed
  template:
    metadata:
      labels:
        app: udagram-backend-feed
    spec:
      containers:
      - image: thecoderocket/udagram-api-feed:v1
        name: udagram-backend-feed
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret 