apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-backend-user
  name: udagram-backend-user
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-backend-user
