apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  namespace: default
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name:  udagram-frontend
        image: thecoderocket/udagram-frontend:v1
        imagePullPolicy: Always  
      restartPolicy: Always
