apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  namespace: default
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: thecoderocket/reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always              
        ports:
        - containerPort: 8080
      restartPolicy: Always