# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag thecoderocket/udagram—frontend:v2 thecoderocket/udagram—frontend:v2
    - run: docker tag thecoderocket/udagram—api-user:v2 thecoderocket/udagram—api-user:v2
    - run: docker tag thecoderocket/udagram—api-feed:v2 thecoderocket/udagram—api-feed:v2
    - run: docker tag thecoderocket/reverseproxy:v2 thecoderocket/reverseproxy:v2

    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - run: docker push thecoderocket/udagram—frontend:v2
    - run: docker push thecoderocket/udagram—api-user:v2
    - run: docker push thecoderocket/udagram—api-feed:v2
    - run: docker push thecoderocket/reverseproxy:v2

